# Generated by Django 3.1.7 on 2021-03-15 16:45

from django.db import migrations, models


def initial_token_data(apps, schema_editor):
    Token = apps.get_model("stocks", "Token")
    db_alias = schema_editor.connection.alias
    Token.objects.using(db_alias).bulk_create([
        Token(key="tinkoff", value="1"),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('figi', models.CharField(max_length=12)),
                ('interval', models.CharField(choices=[('1min', '1min'), ('2min', '2min'), ('3min', '3min'), ('5min', '5min'), ('10min', '10min'), (
                    '15min', '15min'), ('30min', '30min'), ('hour', 'hour'), ('day', 'day'), ('week', 'week'), ('month', 'month')], max_length=10)),
                ('o', models.FloatField()),
                ('c', models.FloatField()),
                ('h', models.FloatField()),
                ('l', models.FloatField()),
                ('v', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('ticker', models.CharField(max_length=10,
                                            primary_key=True, serialize=False)),
                ('figi', models.CharField(max_length=12)),
                ('isin', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(choices=[
                 ('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3)),
                ('lot', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=100,
                                         primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddIndex(
            model_name='candle',
            index=models.Index(
                fields=['figi', 'interval'], name='figi_interval_idx'),
        ),
        migrations.AddIndex(
            model_name='candle',
            index=models.Index(
                fields=['figi', 'interval', 'time'], name='unique_idx'),
        ),
        migrations.AddConstraint(
            model_name='candle',
            constraint=models.UniqueConstraint(
                fields=('figi', 'interval', 'time'), name='unique_candle'),
        ),

        migrations.RunPython(initial_token_data)
    ]
