# Generated by Django 3.1.7 on 2021-03-12 17:21

from django.db import migrations, models


def initial_token_data(apps, schema_editor):
    Token = apps.get_model("stocks", "Token")
    db_alias = schema_editor.connection.alias
    Token.objects.using(db_alias).bulk_create([
        Token(key="tinkoff", value="1"),
        Token(key="tinkoff_sandbox", value="1"),
    ])

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('ticker', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('figi', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=512)),
            ],
        ),

        migrations.RunPython(initial_token_data)
    ]
