# Generated by Django 3.1.7 on 2021-03-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='figi',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='ticker',
            field=models.CharField(max_length=20),
        ),
    ]
