# Generated by Django 3.1.7 on 2021-03-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20210313_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('ticker', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('figi', models.CharField(max_length=12)),
                ('isin', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3)),
                ('lot', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Symbol',
        ),
    ]
